version: "3.1"

services:
  db:
    image: ziggy.db.elephantsql.com
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: xurqrbqm
      POSTGRES_PASSWORD: gcVjLUazgaPU1oI3yM9L2TWPPM6isbF2

  api:
    build: .
    image: thinkful-ed/zid-be-project-movie-01-qualified
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgres://xurqrbqm:gcVjLUazgaPU1oI3yM9L2TWPPM6isbF2@ziggy.db.elephantsql.com:5432/xurqrbqm
